build: off

environment:
  test_script: 'npm run test'

  matrix:
    - nodejs_version: '6'
    - nodejs_version: '4'
      test_script: 'feature-test'
    - nodejs_version: '0.12'
      test_script: 'feature-test'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run %test_script%
